version: '3.5'

services:
  cb-assistant:
    container_name: cb-assistant
    build:
      context: ./packages/ai-agent/
      dockerfile: Docker.assistant
    volumes:
    - ./:/app
    environment:
      - BANK_API=http://cb-bank:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn ai-agent.app:app --reload --host=0.0.0.0 --port 8000
    ports:
      - 5002:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cbnet

  cb-bank:
    container_name: cb-bank
    build:
      context: ./packages/banking/
      dockerfile: Docker.banking
    volumes:
    - ./:/app
    ports:
      - 5001:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cbnet
    command: uvicorn banking.app:app --host=0.0.0.0 --port 8000

  cb-telegram:
    container_name: cb-telegram
    build:
      context: ./packages/bot_tele/
      dockerfile: Docker.telegram
    volumes:
    - ./:/app
    environment:
      - ASSISTANT_API=http://cb-assistant:8000
      - BANK_API=http://cb-bank:8000
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
    command: python -m bot_tele
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cbnet

  # cb-whatsapp:
  #   container_name: cb-whatsapp
  #   build:
  #     context: ./packages/bot_wha/
  #     dockerfile: Docker.whatsapp
  #   volumes:
  #     - ./packages/bot_wha:/app/bot_wha
  #     - ./packages/bot_wha/auth_beak_bot:/app/bot_wha/auth_beak_bot
  #   environment:
  #     - ASSISTANT_API=http://cb-assistant:8000
  #     - BANK_API=http://cb-bank:8000
  #   command: /bin/sh -c "cd bot_wha && npm run start"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   networks:
  #     - cbnet

networks:
  cbnet:
    driver: bridge


